### ISSUE TITLE
Failed to run on Windows 10

### ISSUE THREAD

**Issue by zhovner** [ribasco/glcd-emulator#9]
Sorry for silly question, but I don't know any Java.   
I've install Java SE `JavaSetup8u251.exe` and `jdk-14.0.1_windows-x64_bin.exe` but still get this error. 
My system is Windows 10.  
I've try to run `GLCD Simulator.exe` from windows command line, but don't get any error message. 

Error messages: 

`Failed to find library`
<img width="100" src="https://user-images.githubusercontent.com/774290/82439899-1f613600-9aa4-11ea-9a86-21511c43af5b.png" />

`Failed to locate JNI_CreateJavaVM`
<img width="150" src="https://user-images.githubusercontent.com/774290/82439922-27b97100-9aa4-11ea-960d-30e182976185.png" />

`Failed to launch JVM`
<img width="100" src="https://user-images.githubusercontent.com/774290/82439951-33a53300-9aa4-11ea-9e79-6ceee9007e92.png" />

**Comment by silbo** [comment]
I am also trying to get it to run on Linux or Mac.

**Comment by ribasco** [comment]
I have halted the development of this project. I am currently in the process of developing a wysiwyg  for u8g2 that will supersede this project. If you have any suggestions to fix this issue, feel free to submit a pull request.
